/**
 * Long-form evergreen guides — US preventive health, screenings, and the wellness industry.
 * Hub pages that link deep into the state × procedure matrix.
 * Each guide targets a high-intent patient question with current USPSTF/ACA evidence.
 */

export interface Guide {
  slug: string;
  title: string;
  description: string;
  intro: string; // HTML
  sections: Array<{ heading: string; html: string }>;
  faqs: Array<{ question: string; answer: string }>;
  category: string;
  updatedAt: string;
}

const u = '2026-04-10';

export const guides: Guide[] = [
  {
    slug: 'uspstf-screenings-by-age',
    title: 'USPSTF Recommended Screenings by Age: What You Should Actually Get',
    description: 'The US Preventive Services Task Force recommendations by age and sex, what counts as Grade A or B (and why that matters for ACA coverage), and which routine "annual physical" tests you don\'t need.',
    category: 'Preventive Care',
    updatedAt: u,
    intro: `<p>The US Preventive Services Task Force (USPSTF) is the closest thing the United States has to a national authority on what preventive health services actually save lives. Its recommendations are evidence-based, regularly updated, and crucially, they determine what your health insurance must cover at 100% under the Affordable Care Act. Yet most patients (and many doctors) still treat the "annual physical" as a one-size-fits-all checkup with tests that USPSTF says do not improve outcomes. This guide explains the USPSTF recommendations by age, what's free under ACA, and what you should actually ask for at your next visit.</p>`,
    sections: [
      {
        heading: 'How USPSTF grades recommendations',
        html: `<p>USPSTF assigns each preventive service a letter grade based on the strength of evidence and net benefit:</p><ul><li><strong>Grade A:</strong> high certainty of substantial net benefit. Strongly recommended.</li><li><strong>Grade B:</strong> high certainty of moderate net benefit, or moderate certainty of substantial net benefit. Recommended.</li><li><strong>Grade C:</strong> moderate certainty of small net benefit. Recommend selectively for individual patients.</li><li><strong>Grade D:</strong> moderate or high certainty that the service has no net benefit or that harms outweigh benefits. Recommend AGAINST.</li><li><strong>Grade I:</strong> insufficient evidence to assess balance of benefits and harms.</li></ul><p>Under the Affordable Care Act, insurance plans (with limited grandfather exceptions) must cover Grade A and B services at 100% with no copay, deductible, or coinsurance. Grade C and D services are not covered free, and Grade D services should generally not be performed at all.</p>`,
      },
      {
        heading: 'Recommendations for adults 18-39',
        html: `<p>Grade A and B recommendations for younger adults:</p><ul><li><strong>Blood pressure screening</strong> (Grade A): every 3-5 years for ages 18-39 with normal BP; annual for those with elevated BP or risk factors</li><li><strong>Cholesterol screening</strong> (Grade B for some): for adults 40-75 with risk factors. Younger adults only with significant family history or other risk factors.</li><li><strong>Cervical cancer screening</strong> (Grade A): for women 21-65. Pap smear every 3 years (21-29), or Pap+HPV co-test every 5 years (30-65)</li><li><strong>HIV screening</strong> (Grade A): one-time for adults 15-65, more frequently if at increased risk</li><li><strong>Hepatitis C screening</strong> (Grade B): one-time for adults 18-79</li><li><strong>Tobacco use counseling</strong> (Grade A): annual screening, intervention if positive</li><li><strong>Obesity screening and behavioral counseling</strong> (Grade B): annual BMI calculation, intensive behavioral interventions for BMI ≥30</li><li><strong>Depression screening</strong> (Grade B): once during routine care, with adequate follow-up</li><li><strong>Unhealthy alcohol use screening</strong> (Grade B): adults 18+ in primary care</li><li><strong>Diabetes screening</strong> (Grade B): adults 35-70 who are overweight or obese</li></ul><p>Notably absent: routine annual physical exam, comprehensive metabolic panel, EKG, chest X-ray, urinalysis. USPSTF does not recommend these as routine for healthy young adults.</p>`,
      },
      {
        heading: 'Recommendations for adults 40-64',
        html: `<p>Adds these to the 18-39 list:</p><ul><li><strong>Breast cancer screening</strong> (Grade B): biennial mammography for women 40-74. Updated 2024 — previously 50-74.</li><li><strong>Colorectal cancer screening</strong> (Grade A): adults 45-75. Multiple options: colonoscopy every 10 years, FIT annually, sigmoidoscopy every 5 years, FIT-DNA every 1-3 years.</li><li><strong>Lung cancer screening</strong> (Grade B): adults 50-80 with 20+ pack-year smoking history who currently smoke or quit within 15 years. Annual low-dose CT.</li><li><strong>Cholesterol/statin therapy</strong> (Grade B): statins for primary prevention in adults 40-75 with at least one CVD risk factor and 10-year CVD risk ≥10%</li><li><strong>Diabetes screening</strong> (Grade B): adults 35-70 who are overweight or obese (continues from younger adults)</li><li><strong>Hepatitis B screening</strong> (Grade B): adolescents and adults at increased risk</li><li><strong>Osteoporosis screening</strong> (Grade B): women 65+ (and women under 65 at high fracture risk)</li><li><strong>Aspirin for CVD prevention</strong> (Grade C): individual decision for adults 40-59 with 10%+ CVD risk; recommend AGAINST for adults 60+ as primary prevention</li></ul>`,
      },
      {
        heading: 'Recommendations for adults 65+',
        html: `<p>Adds these to the middle-aged list:</p><ul><li><strong>Abdominal aortic aneurysm screening</strong> (Grade B): one-time ultrasound for men 65-75 who have ever smoked</li><li><strong>Falls prevention</strong> (Grade B): exercise interventions for adults 65+ at increased risk</li><li><strong>Vision screening</strong> for older adults (some grades vary)</li><li><strong>Hearing loss screening</strong> (Grade I): insufficient evidence — but commonly done despite lack of formal recommendation</li></ul><p>Important: many screenings have UPPER age limits where USPSTF either recommends against or finds insufficient evidence. Examples:</p><ul><li>Cervical cancer screening: stop at 65 if adequate prior screening</li><li>Mammography: stop at 75 (limited benefit beyond)</li><li>Colorectal cancer screening: individualize 76-85, recommend against 86+</li><li>Lung cancer screening: stop at 81</li><li>Prostate cancer screening (PSA): individual decision 55-69, recommend against 70+</li></ul><p>Continuing screenings beyond these ages provides little to no benefit and exposes patients to harms (false positives, overdiagnosis, anxiety, unnecessary biopsies). The "more screening is always better" assumption is demonstrably wrong for elderly patients.</p>`,
      },
      {
        heading: 'Tests USPSTF recommends AGAINST',
        html: `<p>Several common tests have Grade D ("recommend against") ratings:</p><ul><li><strong>Routine annual physical for healthy adults:</strong> not recommended. The "annual physical" tradition has no evidence base. Targeted screenings based on age and risk are sufficient.</li><li><strong>Routine EKG screening for cardiovascular disease in asymptomatic low-risk adults:</strong> Grade D</li><li><strong>Routine carotid artery stenosis screening for asymptomatic adults:</strong> Grade D</li><li><strong>PSA screening for prostate cancer in men 70+:</strong> Grade D</li><li><strong>Vitamin D testing for healthy adults:</strong> Grade I (insufficient evidence) — generally not recommended</li><li><strong>Genetic testing for BRCA in women without family history of breast/ovarian cancer:</strong> Grade D</li><li><strong>Comprehensive whole-body CT or MRI screening:</strong> never recommended</li></ul><p>If your doctor orders any of these as routine, ask why. Sometimes there's a specific clinical reason; often it's defensive medicine or chargemaster-driven test ordering.</p>`,
      },
      {
        heading: 'How to use USPSTF for your own care',
        html: `<p>Three steps to get the right preventive care:</p><ol><li><strong>Look up your age-appropriate Grade A and B recommendations</strong> at uspreventiveservicestaskforce.org. Print the list.</li><li><strong>Bring it to your next doctor visit</strong> and ask which screenings you need now. Some you may have already had recently; others may be due.</li><li><strong>Confirm with your insurance plan</strong> that the screening is covered at 100% under ACA preventive care. Use the exact CPT code if possible.</li></ol><p>Watch for these common pitfalls:</p><ul><li><strong>Diagnostic vs screening distinction:</strong> if a screening test finds something that requires follow-up testing, the follow-up is typically NOT free under ACA. A free screening colonoscopy that finds polyps may become a billable diagnostic procedure if biopsies are taken.</li><li><strong>Doctor visit fee:</strong> the screening itself may be free, but the visit during which the doctor orders or discusses it may have a copay or coinsurance.</li><li><strong>Out-of-network providers:</strong> screening at an out-of-network facility loses ACA preventive coverage. Always verify network status.</li></ul>`,
      },
    ],
    faqs: [
      { question: 'What is USPSTF?', answer: 'The US Preventive Services Task Force, an independent panel of national experts that makes evidence-based recommendations on preventive care. Its Grade A and B recommendations must be covered at 100% by most health insurance plans under the Affordable Care Act.' },
      { question: 'Which preventive services are free under ACA?', answer: 'Services rated Grade A or B by USPSTF, plus immunizations recommended by ACIP, plus the preventive care list for women (HRSA) and children (Bright Futures). Includes blood pressure, cholesterol, cancer screenings (cervical, colorectal, breast, lung when eligible), diabetes screening, depression screening, immunizations, and many more.' },
      { question: 'Should I get an annual physical?', answer: 'USPSTF does not recommend a routine annual physical for healthy adults. Instead, get age-appropriate Grade A and B preventive services. The "annual physical" tradition predates evidence-based medicine and has no demonstrated benefit for asymptomatic adults.' },
      { question: 'When should I start mammography?', answer: 'Per USPSTF 2024 update, biennial mammography for women 40-74 (Grade B). Previous recommendation was 50-74. Some specialty groups (American Cancer Society) recommend starting at 45. Discuss with your doctor based on personal and family history.' },
      { question: 'When should I get a colonoscopy?', answer: 'USPSTF recommends colorectal cancer screening starting at age 45 (Grade A). Options include colonoscopy every 10 years, FIT (fecal immunochemical test) annually, sigmoidoscopy every 5 years, or FIT-DNA every 1-3 years. Stop routine screening at 76-85 (individualize) and definitely by 86.' },
      { question: 'Why is PSA screening controversial?', answer: 'Because the evidence shows PSA screening has small benefits (slightly fewer prostate cancer deaths) and substantial harms (overdiagnosis, unnecessary biopsies, treatment side effects). USPSTF recommends individual decision-making for men 55-69 and recommends AGAINST PSA screening for men 70+.' },
      { question: 'What does it mean if my doctor orders a Grade D test?', answer: 'It means USPSTF actively recommends against that test (the harms outweigh the benefits for routine use). Sometimes there\'s a specific clinical reason for ordering it anyway. Ask your doctor: "USPSTF gives this a Grade D — what\'s the specific reason for ordering it for me?" The answer should reference your individual situation.' },
    ],
  },
  {
    slug: 'aca-preventive-care-coverage',
    title: 'Free Preventive Care Under ACA: What\'s Covered and What Isn\'t',
    description: 'The complete list of preventive services covered at 100% under the Affordable Care Act, the screening-vs-diagnostic trap that turns free care into expensive bills, and grandfathered plan exceptions.',
    category: 'Insurance Coverage',
    updatedAt: u,
    intro: `<p>One of the most valuable provisions of the Affordable Care Act is the requirement that most health insurance plans cover preventive care services at 100% — no copay, no deductible, no coinsurance. This includes cancer screenings, immunizations, contraception, and many other services that cost thousands out of pocket before ACA. Yet most patients don't know exactly what's covered, and many get surprise bills when "free" preventive care becomes "diagnostic" care during the same visit. This guide explains exactly what's covered, the rules for grandfathered plans, and the screening-vs-diagnostic trap that catches patients off guard.</p>`,
    sections: [
      {
        heading: 'The 4 categories of free preventive care',
        html: `<p>Under the ACA, non-grandfathered insurance plans must cover four categories of preventive services with no cost-sharing:</p><ol><li><strong>USPSTF Grade A and B recommendations</strong> (the largest category — see our <a href="/guide/uspstf-screenings-by-age/">USPSTF guide</a>)</li><li><strong>ACIP-recommended immunizations</strong> for children, adolescents, and adults</li><li><strong>HRSA-supported preventive care for women</strong> (contraception, breastfeeding support, well-woman visits)</li><li><strong>HRSA Bright Futures preventive care for infants, children, and adolescents</strong></li></ol><p>The combined list includes about 60+ specific services. The Department of Health and Human Services maintains the complete list at healthcare.gov/coverage/preventive-care-benefits/.</p>`,
      },
      {
        heading: 'Adult preventive services covered at 100%',
        html: `<p>The most commonly used adult preventive services covered free under ACA:</p><ul><li>Abdominal aortic aneurysm screening (one-time, men 65-75 who smoked)</li><li>Alcohol misuse screening and counseling</li><li>Aspirin use to prevent CVD (for adults 40-59 at high risk)</li><li>Blood pressure screening</li><li>Cholesterol screening (men 35+ and women 45+, or earlier if high risk)</li><li>Colorectal cancer screening (45-75)</li><li>Depression screening</li><li>Diabetes (Type 2) screening (overweight adults 35-70)</li><li>Diet counseling for adults at higher risk for chronic disease</li><li>Hepatitis B screening (high risk)</li><li>Hepatitis C screening (one-time for adults 18-79)</li><li>HIV screening (15-65, plus pregnant women)</li><li>Immunizations: flu, COVID-19, Tdap, MMR, varicella, HPV, pneumococcal, shingles, hepatitis A and B</li><li>Lung cancer screening (50-80 with smoking history)</li><li>Obesity screening and counseling</li><li>Sexually transmitted infection prevention counseling</li><li>Statin preventive medication</li><li>Syphilis screening</li><li>Tobacco use screening and cessation interventions</li></ul><p>Women-specific (additional under HRSA):</p><ul><li>Breast cancer screening (mammography)</li><li>Breastfeeding support, supplies, and counseling</li><li>Cervical cancer screening</li><li>Contraception (FDA-approved methods, all 18 categories, with limited religious exemptions)</li><li>Domestic violence screening and counseling</li><li>Folic acid supplements (women planning pregnancy)</li><li>Gestational diabetes screening</li><li>HPV DNA test</li><li>Osteoporosis screening (65+ and earlier with risk factors)</li><li>Well-woman visits</li></ul>`,
      },
      {
        heading: 'The screening-vs-diagnostic trap',
        html: `<p>The single most common reason patients get surprise bills for "free" preventive care is the screening-to-diagnostic transition. Here's how it works:</p><p><strong>Screening:</strong> a test performed on a healthy person without symptoms to look for early disease. ACA covers screenings at 100% for Grade A/B services.</p><p><strong>Diagnostic:</strong> a test performed because of symptoms, abnormal findings, or follow-up to a positive screening. NOT covered at 100%; subject to normal deductible and coinsurance.</p><p>Examples where screening becomes diagnostic:</p><ol><li><strong>Screening colonoscopy that finds polyps:</strong> if the gastroenterologist removes the polyps during the same procedure (which is routine), the procedure is reclassified as diagnostic. Free becomes $1,000-$3,000.</li><li><strong>Screening mammogram with abnormal finding:</strong> if you need additional imaging (diagnostic mammogram, ultrasound, biopsy), the follow-up is diagnostic and billed normally.</li><li><strong>Routine well-woman visit where you mention a specific symptom:</strong> the visit may be coded as a problem-focused visit instead of preventive, losing the free coverage.</li><li><strong>Cholesterol screening that finds high cholesterol:</strong> the screening itself is free, but follow-up tests and treatment are diagnostic.</li></ol><p>Workarounds:</p><ul><li>Schedule preventive visits as preventive only — don't bring up new problems during the visit. Schedule a separate problem-focused visit if needed.</li><li>Ask the provider before the visit how they will code the visit. "Will this be billed as preventive (USPSTF Grade A/B) or diagnostic?"</li><li>For screening colonoscopy, ask about polyp removal coverage. Some plans (Medicare, others) treat this as covered preventive even when polyps are removed.</li></ul>`,
      },
      {
        heading: 'Grandfathered plans: the exception',
        html: `<p>Health plans in existence before March 23, 2010 ("grandfathered" plans) are NOT required to provide free preventive care under ACA. They retain the rules of the older plan as long as they don't make significant changes (raising copays or deductibles too much, reducing benefits, switching insurers).</p><p>About 13% of US workers were still on grandfathered plans as of recent years, though the number is shrinking as employers make changes that void grandfather status.</p><p>If you're on a grandfathered plan, your preventive care may be subject to copays and deductibles. Check your Summary of Benefits and Coverage document or call your plan to verify. If your plan is grandfathered, you may want to push your employer to switch to a non-grandfathered plan, which provides better benefits.</p>`,
      },
      {
        heading: 'Religious exemptions',
        html: `<p>Two narrow exceptions to ACA preventive coverage:</p><ul><li><strong>Houses of worship:</strong> churches, temples, mosques are exempt from the contraception coverage requirement.</li><li><strong>Religious nonprofits and certain for-profits:</strong> can opt out of contraception coverage. The Trump administration expanded these exemptions; the Biden administration narrowed them. The current rules are in flux.</li></ul><p>If your employer plan does not cover contraception due to a religious exemption, you may be able to access contraception through:</p><ul><li>Federally funded health centers (sliding scale)</li><li>Title X family planning clinics</li><li>Direct purchase from a separate insurer or pharmacy</li><li>State Medicaid (if eligible)</li></ul>`,
      },
      {
        heading: 'How to maximize your free preventive care',
        html: `<ol><li><strong>Get your age-appropriate preventive services every year.</strong> The "annual" visit terminology is misleading — different services have different intervals. Track which screenings you've had and when.</li><li><strong>Know the USPSTF grades for your services.</strong> Only Grade A and B services are covered free. Grade C and D services may not be (and Grade D shouldn't generally be done at all).</li><li><strong>Schedule preventive visits separately from problem visits.</strong> Don't bring up new symptoms during a preventive visit.</li><li><strong>Verify in-network status</strong> for any preventive care provider. Out-of-network preventive care loses the ACA cost-sharing protections.</li><li><strong>Understand the screening-to-diagnostic transition</strong> and ask about it before any procedure that might find something (colonoscopy, mammogram).</li><li><strong>If you're charged for a preventive service that should be free</strong>, file an appeal with your insurance company. Cite the USPSTF recommendation grade and the ACA preventive care requirement. Most appeals are successful when the service clearly meets the criteria.</li></ol>`,
      },
    ],
    faqs: [
      { question: 'What preventive services are free under ACA?', answer: 'USPSTF Grade A and B recommendations, ACIP-recommended immunizations, HRSA-supported women\'s preventive care, and HRSA Bright Futures pediatric care. The combined list includes about 60+ services and is published at healthcare.gov/coverage/preventive-care-benefits/.' },
      { question: 'Why was I charged for a free preventive service?', answer: 'Most commonly because the service was reclassified as diagnostic instead of screening. A screening colonoscopy that removes polyps becomes a diagnostic procedure. A mammogram with abnormal findings leads to billable follow-up. Always ask before the procedure how it will be coded.' },
      { question: 'Are all health plans required to cover preventive care for free?', answer: 'No. Grandfathered plans (those in existence before March 23, 2010 that have not made significant changes) are exempt. About 13% of US workers were still on grandfathered plans as of recent years. Check your Summary of Benefits and Coverage to verify.' },
      { question: 'Is birth control covered free under ACA?', answer: 'Yes, all 18 FDA-approved categories of contraception are covered at 100% under ACA for women, with limited religious exemptions. Includes pills, IUDs, implants, sterilization, and emergency contraception. Some employers with religious objections can opt out.' },
      { question: 'What is the difference between screening and diagnostic tests?', answer: 'A screening test is performed on a healthy person without symptoms to detect early disease. A diagnostic test is performed because of symptoms, abnormal findings, or follow-up to a positive screening. Only screening tests get the ACA free preventive care coverage; diagnostic tests are subject to normal cost-sharing.' },
      { question: 'How do I appeal a charge for a service that should have been free?', answer: 'File an internal appeal with your insurance company within 180 days. Cite the USPSTF recommendation grade and the ACA preventive care requirement. If denied, file an external appeal with an Independent Review Organization. Many denials are overturned at the external appeal level when the service clearly meets the criteria.' },
    ],
  },
  {
    slug: 'cancer-screening-cost-benefit',
    title: 'Cancer Screening Cost-Benefit: Which Tests Save Lives vs Cause Harm',
    description: 'A look at the actual evidence on cancer screening: number needed to screen, overdiagnosis rates, why some screenings save lives and others cause net harm, and which tests USPSTF actually recommends.',
    category: 'Screening Evidence',
    updatedAt: u,
    intro: `<p>The intuition is simple: more cancer screening is always better, right? Catch it early, treat it early, save lives. The evidence is more complicated. Some cancer screenings have clear benefits (colorectal cancer screening saves about 1 in 100 screened over a decade). Others have small benefits offset by substantial harms (PSA testing has been controversial for 20 years). Some have no benefit at all and are recommended against (whole-body CT scans). This guide walks through the actual evidence on the major cancer screenings, the concept of "number needed to screen," and how to make informed decisions about which to get.</p>`,
    sections: [
      {
        heading: 'How to evaluate a cancer screening test',
        html: `<p>Evidence-based screening evaluation looks at five questions:</p><ol><li><strong>Does the screening reduce cancer-specific mortality?</strong> Not just "find more cancers" — does it actually save lives from that cancer?</li><li><strong>Does it reduce all-cause mortality?</strong> Catching cancer earlier doesn't always extend lifespan if treatment harms or other causes of death dominate.</li><li><strong>What is the number needed to screen (NNS)?</strong> How many people need to be screened to prevent one death? Lower numbers = better screening.</li><li><strong>What is the rate of overdiagnosis?</strong> Detection of cancers that would never have caused symptoms or death if untreated.</li><li><strong>What are the harms?</strong> False positives, biopsies, anxiety, treatment side effects, complications.</li></ol><p>A "good" screening test has high mortality reduction, low NNS, low overdiagnosis, and acceptable harms. A "bad" screening test fails one or more of these tests.</p>`,
      },
      {
        heading: 'Colorectal cancer screening: the clearest win',
        html: `<p>Colorectal cancer screening has the strongest evidence base of any cancer screening. The mortality reduction is substantial and well-documented across multiple methods.</p><p>Evidence:</p><ul><li><strong>Mortality reduction:</strong> 25-30% reduction in colorectal cancer deaths</li><li><strong>Number needed to screen:</strong> approximately 1 in 100 people screened over 10 years avoids a colorectal cancer death</li><li><strong>All-cause mortality:</strong> small but measurable reduction</li><li><strong>Overdiagnosis:</strong> low (most polyps progress to cancer if untreated)</li><li><strong>Harms:</strong> bowel perforation in colonoscopy (1 in 1,000), bleeding from polyp removal, false positives in stool tests</li></ul><p>USPSTF recommends colorectal cancer screening for adults 45-75 (Grade A), individualized 76-85, against 86+. Multiple methods are equally acceptable:</p><ul><li>Colonoscopy every 10 years (most common, also therapeutic)</li><li>FIT (fecal immunochemical test) annually</li><li>Sigmoidoscopy every 5 years (less common)</li><li>FIT-DNA (Cologuard) every 1-3 years</li><li>CT colonography every 5 years</li></ul><p>FIT is the most evidence-supported and least invasive option. Colonoscopy is more thorough but more invasive and expensive. Choose based on access, preference, and tolerance.</p>`,
      },
      {
        heading: 'Breast cancer screening: meaningful but contested',
        html: `<p>Mammography for breast cancer screening has more contested evidence. Benefits exist but are smaller than commonly believed, and harms (false positives, overdiagnosis) are significant.</p><p>Evidence:</p><ul><li><strong>Mortality reduction:</strong> approximately 15-20% reduction in breast cancer deaths</li><li><strong>Number needed to screen:</strong> approximately 1 in 1,000 women screened for 10 years avoids a breast cancer death (much higher NNS than colorectal)</li><li><strong>Overdiagnosis:</strong> meaningful — estimates range from 10-30% of screen-detected cancers would never have caused symptoms or death</li><li><strong>False positive rate:</strong> approximately 50% of women screened over 10 years will have at least one false positive requiring additional testing</li><li><strong>Biopsy rate:</strong> approximately 7-10% will have at least one biopsy over 10 years</li></ul><p>USPSTF 2024 update: biennial mammography for women 40-74 (Grade B). Previously was 50-74. The update reflects new evidence on younger women, particularly Black women who have higher rates of aggressive cancers at younger ages.</p><p>Recommendations vary by organization. American Cancer Society recommends starting at 45 with annual screening 45-54, biennial 55+. Some breast cancer organizations recommend annual starting at 40. Discuss with your doctor based on personal and family history.</p>`,
      },
      {
        heading: 'PSA screening for prostate cancer: the controversial case',
        html: `<p>PSA (Prostate-Specific Antigen) screening for prostate cancer is the most controversial cancer screening in modern medicine. The evidence has shifted USPSTF recommendations multiple times.</p><p>Evidence:</p><ul><li><strong>Mortality reduction:</strong> small — approximately 1 in 1,000 men screened for 10 years avoids a prostate cancer death</li><li><strong>Number needed to screen:</strong> very high (1,000+ to prevent one death)</li><li><strong>Overdiagnosis:</strong> very high — many prostate cancers grow slowly and would never cause symptoms in the man's lifetime. Estimates suggest 20-50% of screen-detected cancers are overdiagnosed.</li><li><strong>Harms:</strong> biopsy complications, anxiety, treatment side effects (incontinence in 10-20%, erectile dysfunction in 30-60%, bowel problems in 5-10% after surgery or radiation)</li></ul><p>USPSTF current recommendation:</p><ul><li><strong>Men 55-69:</strong> Grade C — individual decision based on personal preferences. Discuss benefits and harms with doctor.</li><li><strong>Men 70+:</strong> Grade D — recommend AGAINST screening. Harms outweigh benefits for older men.</li></ul><p>The "active surveillance" approach has become more common for low-grade prostate cancers, allowing many men to avoid treatment side effects while still monitoring the cancer. If you have PSA screening done, discuss the active surveillance option before any treatment.</p>`,
      },
      {
        heading: 'Lung cancer screening: targeted, not universal',
        html: `<p>Lung cancer screening with low-dose CT is recommended only for a specific high-risk group, not the general population.</p><p>Evidence:</p><ul><li><strong>Mortality reduction:</strong> 20-25% reduction in lung cancer deaths in heavy smokers</li><li><strong>NNS:</strong> approximately 1 in 320 in the screening eligible population</li><li><strong>False positive rate:</strong> 25-50% will have at least one false positive over 3 years of annual screening</li><li><strong>Overdiagnosis:</strong> moderate (some cancers found wouldn\'t have caused symptoms)</li></ul><p>USPSTF Grade B recommendation: annual low-dose CT for adults 50-80 with:</p><ul><li>20+ pack-year smoking history (e.g., 1 pack/day for 20 years, or 2 packs/day for 10 years)</li><li>Currently smoke OR quit within the last 15 years</li></ul><p>Stop screening when 15 years have passed since quitting, or when health problems substantially limit life expectancy or surgical candidacy.</p><p>Not recommended for never-smokers, light smokers, or adults outside the 50-80 age range. The mortality benefit only emerges in the high-risk subgroup.</p>`,
      },
      {
        heading: 'Cancer screenings recommended AGAINST',
        html: `<p>USPSTF actively recommends AGAINST several cancer screenings:</p><ul><li><strong>Whole-body CT or MRI screening</strong> (offered by some commercial wellness companies for $1,000-$3,000): no mortality benefit, high false positive rate, radiation exposure for CT</li><li><strong>Pancreatic cancer screening in average-risk adults</strong> (Grade D): no effective screening test, poor outcomes regardless</li><li><strong>Ovarian cancer screening with CA-125 or ultrasound</strong> in average-risk women (Grade D): no mortality benefit, high false positive rate, harms from unnecessary surgery</li><li><strong>Testicular cancer screening</strong> in adolescents and men (Grade D): no clinical exam benefit shown</li><li><strong>Thyroid cancer screening</strong> in adults (Grade D): high false positive rate, overdiagnosis of indolent cancers</li><li><strong>Bladder cancer screening</strong> in adults (Grade I): insufficient evidence, generally not recommended</li></ul><p>If a wellness clinic, executive physical program, or other provider offers these tests, the answer should generally be no. The evidence shows they cause more harm than benefit at the population level.</p>`,
      },
    ],
    faqs: [
      { question: 'Which cancer screenings actually save lives?', answer: 'Colorectal cancer screening (strongest evidence, NNS about 1 in 100 over 10 years), breast cancer screening for women 40-74 (smaller benefit, NNS about 1 in 1,000), cervical cancer screening, lung cancer screening for heavy smokers 50-80. PSA prostate screening is controversial with small benefits and large harms.' },
      { question: 'What is "number needed to screen"?', answer: 'How many people need to be screened to prevent one death from the cancer being screened. Lower numbers indicate more effective screening. Colorectal cancer: ~100 people for 10 years. Breast cancer: ~1,000 women. PSA: ~1,000-2,000 men. Higher NNS means more people undergo screening for each life saved.' },
      { question: 'Why is PSA screening controversial?', answer: 'Because the evidence shows small mortality benefit, very high overdiagnosis rate, and substantial harms from treatment (incontinence, erectile dysfunction, bowel problems). USPSTF recommends individual decision-making for men 55-69 and recommends AGAINST screening for men 70+. The active surveillance approach has reduced harm in recent years.' },
      { question: 'Should I get a whole-body MRI scan?', answer: 'No, USPSTF and major medical organizations recommend against routine whole-body imaging. There is no evidence of mortality benefit, the false positive rate is high, and incidental findings lead to unnecessary follow-up testing and procedures. Wellness clinics offering these scans for $1,000-$3,000 have no evidence base.' },
      { question: 'Should I start mammography at 40 or 50?', answer: 'USPSTF 2024 update recommends starting at 40 (Grade B), changed from the previous 50. Some organizations recommend starting at 45 (American Cancer Society) or 40 (American College of Radiology). The "right" answer depends on personal risk factors and preferences. Discuss with your doctor.' },
      { question: 'What is overdiagnosis?', answer: 'Detection of cancers through screening that would never have caused symptoms or death if left untreated. Overdiagnosis leads to unnecessary treatment with real side effects. Common in slow-growing cancers like prostate (20-50% overdiagnosis), thyroid, and some breast cancers (10-30%).' },
      { question: 'Should I get lung cancer screening?', answer: 'Only if you meet the high-risk criteria: age 50-80, 20+ pack-year smoking history, currently smoke or quit within 15 years. Annual low-dose CT scan for this group reduces lung cancer deaths by 20-25%. Not recommended for never-smokers, light smokers, or those outside the eligible age range.' },
    ],
  },
  {
    slug: 'executive-physical-vs-standard',
    title: 'Executive Physical vs Standard: What $2,000 Buys You (and What It Doesn\'t)',
    description: 'How "executive physical" programs work, what they include beyond standard preventive care, the unnecessary tests they often add, and whether they actually improve health outcomes.',
    category: 'Medical Marketing',
    updatedAt: u,
    intro: `<p>Executive physicals are comprehensive medical examinations marketed to busy professionals, typically costing $1,500 to $5,000 per visit. They promise comprehensive screening, advanced testing, and personalized health insights. The reality is more complicated. Most of the value comes from a few core preventive services that are also covered free under standard insurance. Many of the additional tests in executive physicals have no evidence base, and some are actively harmful through overdiagnosis. This guide explains what executive physicals include, what's worth paying for, and what you'd be paying for that has zero evidence of benefit.</p>`,
    sections: [
      {
        heading: 'What an executive physical typically includes',
        html: `<p>A typical executive physical from a hospital-affiliated program (Mayo Clinic, Cleveland Clinic, Johns Hopkins, Mass General, or similar) takes 4-8 hours and includes:</p><ul><li><strong>Comprehensive history and physical examination</strong> by an internal medicine physician</li><li><strong>Comprehensive labs:</strong> CBC, CMP, lipid panel, HbA1c, thyroid function, urinalysis, often vitamin D, vitamin B12, ferritin, and inflammatory markers</li><li><strong>Chest X-ray</strong> (sometimes)</li><li><strong>EKG</strong> at rest</li><li><strong>Cardiovascular testing:</strong> often a stress test or echocardiogram</li><li><strong>Cancer screenings</strong> per USPSTF (mammography, colonoscopy, PSA if discussed)</li><li><strong>Pulmonary function testing</strong></li><li><strong>Vision and hearing screening</strong></li><li><strong>Body composition analysis</strong></li><li><strong>Nutrition consultation</strong></li><li><strong>Fitness consultation and exercise prescription</strong></li><li><strong>Sometimes:</strong> CT scan (chest, abdomen, or whole body), CIMT (carotid intima-media thickness), advanced lipid panel, genetic testing, microbiome analysis</li></ul><p>Total cost: $1,500-$5,000+ depending on facility and components. Usually paid out of pocket since most insurance won't cover the full bundled package.</p>`,
      },
      {
        heading: 'What\'s worth paying for',
        html: `<p>Most of the value of an executive physical comes from a small subset of components that have evidence-based benefit:</p><ol><li><strong>Comprehensive USPSTF Grade A and B preventive services.</strong> Cancer screenings, blood pressure, cholesterol, diabetes screening, vaccinations. These are covered FREE under your standard insurance. You don't need an executive physical to get them.</li><li><strong>Long doctor consultation time.</strong> Executive physicals typically include 60-90 minutes with a doctor versus 15-20 minutes in standard care. This time can be valuable for discussing complex personal health concerns, family history, lifestyle questions, and medication review. The value is the time, not the special tests.</li><li><strong>Coordination of care.</strong> If you have multiple specialists, an executive physical can coordinate the full picture in one visit. Useful for complex medical histories.</li><li><strong>Convenience and one-stop access.</strong> If you would otherwise skip preventive care entirely due to busy schedule, the executive physical's convenience may have indirect value by ensuring you actually get screening.</li></ol><p>If you can get USPSTF screenings through standard insurance and have a primary care doctor who gives you adequate time, you\'re getting most of the benefit of an executive physical for free.</p>`,
      },
      {
        heading: 'What you\'re paying for that has no evidence',
        html: `<p>Many components of executive physicals are not recommended by USPSTF and may even be harmful:</p><ul><li><strong>Routine EKG:</strong> Grade D for asymptomatic adults. False positives lead to unnecessary cardiology workups.</li><li><strong>Routine stress test:</strong> Grade D for asymptomatic low-risk adults. Does not improve outcomes; false positives are common.</li><li><strong>Whole-body or partial-body CT screening:</strong> never recommended. Radiation exposure, false positives, no mortality benefit. The wellness industry markets these heavily despite the evidence against them.</li><li><strong>CIMT (carotid intima-media thickness):</strong> not recommended for screening. Used in research but not validated for individual patient decision-making.</li><li><strong>Routine pulmonary function testing</strong> in non-smokers: not recommended.</li><li><strong>Vitamin D testing in healthy adults:</strong> Grade I (insufficient evidence) — generally not useful unless symptomatic.</li><li><strong>Routine "wellness" labs:</strong> CRP, homocysteine, advanced lipid panels (LDL particle size), microbiome — not validated for individual patient management.</li><li><strong>Genetic screening</strong> without family history: not recommended for most cancer-related genes.</li></ul><p>These tests are often marketed as "advanced," "comprehensive," or "preventive," but the evidence doesn't support their use in healthy people. They primarily generate false positives that lead to additional testing, anxiety, and procedures.</p>`,
      },
      {
        heading: 'The harm of overdiagnosis',
        html: `<p>The biggest hidden cost of executive physicals is not the price tag — it's the cascade of follow-up testing and procedures triggered by abnormal findings on tests that shouldn't have been done.</p><p>Common scenarios:</p><ul><li><strong>Whole-body CT finds an "incidentaloma"</strong> (a small abnormal finding of unknown significance). Now you need follow-up imaging in 3 months, possibly a year, possibly biopsy. The original "preventive" scan creates ongoing anxiety and cost.</li><li><strong>Stress test shows ambiguous results.</strong> Now you need cardiac catheterization, an invasive procedure with real risks.</li><li><strong>Prostate ultrasound finds a small nodule.</strong> Now you need biopsy, which has 1-3% serious complication rate.</li><li><strong>Genetic test shows a variant of unknown significance.</strong> You can't undo knowing it. Anxiety and possibly unnecessary preventive surgery follow.</li></ul><p>Overdiagnosis is the term for finding diseases that would never have caused symptoms or death if left undetected. Some studies suggest 20-50% of screen-detected cancers in modern screening programs are overdiagnoses. Every overdiagnosed case represents real treatment harm without compensating benefit.</p>`,
      },
      {
        heading: 'When an executive physical is worth it',
        html: `<p>Three situations where the cost may be justified:</p><ol><li><strong>You have specific health concerns that need extended time</strong> with a generalist physician and don't have a primary care doctor. The 60-90 minute visit can be more valuable than multiple short visits.</li><li><strong>You have complex medical history requiring coordination</strong> across specialties. The executive physical provides one place that synthesizes everything.</li><li><strong>You don't have any primary care relationship</strong> and would otherwise skip preventive care entirely. Even with some unnecessary tests, getting the core screenings is better than getting nothing.</li></ol><p>For everyone else, a relationship with a regular primary care physician — annual or as needed — combined with the USPSTF Grade A and B preventive services covered free under ACA, provides the same evidence-based benefit at no out-of-pocket cost.</p>`,
      },
      {
        heading: 'How to get executive physical value without the price',
        html: `<ol><li><strong>Find a primary care physician</strong> who gives you 30-45 minute appointments for annual physical visits. Direct primary care practices ($75-$150/month) typically offer this.</li><li><strong>Request all USPSTF Grade A/B services</strong> appropriate for your age and sex. They're free under ACA.</li><li><strong>Get appropriate cancer screenings</strong> at recommended intervals (colonoscopy, mammography, cervical, lung if eligible).</li><li><strong>Have a longer "annual" visit once a year</strong> to discuss health concerns, lifestyle, and family history. Schedule it as a preventive visit so it's covered.</li><li><strong>Ask your doctor to coordinate</strong> any specialty care you receive. Most internists are happy to do this if asked.</li></ol><p>This DIY approach replicates 80% of what an executive physical delivers at 0% of the cost. The 20% you "miss" is mostly tests with no evidence base.</p>`,
      },
    ],
    faqs: [
      { question: 'Is an executive physical worth it?', answer: 'Usually no for healthy adults with insurance. Most of the evidence-based value (USPSTF screenings, annual preventive care) is covered free under ACA. The "extras" in executive physicals (whole-body CT, stress testing, advanced labs) often have no evidence of benefit and can cause harm through overdiagnosis.' },
      { question: 'What does an executive physical include?', answer: 'Typically a 4-8 hour visit with comprehensive history, physical exam, extensive labs, EKG, often stress testing, vision/hearing, body composition, nutrition and fitness consultation, and sometimes CT scans or advanced testing. Cost: $1,500-$5,000+, usually paid out of pocket.' },
      { question: 'Does insurance cover executive physicals?', answer: 'Usually no. Insurance covers individual preventive services (USPSTF Grade A/B) at 100%, but not the bundled "executive physical" package. The non-evidence-based components (CT scans, advanced labs) are typically not covered by insurance for asymptomatic adults.' },
      { question: 'Why do executive physicals include tests USPSTF recommends against?', answer: 'Marketing differentiation. Hospitals compete on offering "more comprehensive" packages, even when the additional tests have no evidence base. Some are also defensive medicine — ordering more tests reduces malpractice risk if something is later missed.' },
      { question: 'What is overdiagnosis?', answer: 'Detection of diseases (often cancers) through screening that would never have caused symptoms or death if left untreated. Leads to real treatment harms (surgery, radiation, side effects) without compensating benefit. Some studies suggest 20-50% of screen-detected cancers in modern screening programs are overdiagnoses.' },
      { question: 'How can I get the same value as an executive physical for less?', answer: 'Establish a relationship with a primary care doctor (or direct primary care, $75-150/month). Get all USPSTF Grade A/B screenings appropriate for your age (free under ACA). Request a longer annual visit to discuss concerns and lifestyle. This replicates 80% of executive physical value at near-zero out-of-pocket cost.' },
    ],
  },
  {
    slug: 'biomarker-tests-wellness-trap',
    title: 'Biomarker Tests You Probably Don\'t Need: The Wellness Industry Trap',
    description: 'Why direct-to-consumer wellness tests like full-body MRI, microbiome analysis, food sensitivity panels, and DTC genetic tests have no evidence base and how to spot the marketing red flags.',
    category: 'Wellness Industry',
    updatedAt: u,
    intro: `<p>The wellness industry has exploded over the past decade, marketing direct-to-consumer biomarker tests, full-body imaging, genetic testing, microbiome analysis, food sensitivity panels, and "biological age" calculators. Costs range from $100 to $5,000 per test. The marketing implies that more data about your body is always better, that small abnormalities are early warnings, and that "personalized" insights will optimize your health. The evidence shows the opposite for most of these tests: they generate false alarms, lead to unnecessary follow-up, and have no demonstrated improvement in health outcomes. This guide explains the most common wellness tests, what they actually do, and why USPSTF and other evidence-based bodies don't recommend most of them.</p>`,
    sections: [
      {
        heading: 'Why "more data" isn\'t always better',
        html: `<p>The intuition driving wellness testing is appealing: knowing more about your body should help you make better decisions and catch problems earlier. The reality is more complex.</p><p>Three reasons more testing often produces worse outcomes:</p><ol><li><strong>Base rate problem.</strong> When you test for rare conditions in healthy people, false positives outnumber true positives. Even a 95% accurate test for a 1% prevalence condition produces about 5 false positives for every 1 true positive. Most "abnormal" findings in healthy adults are false alarms.</li><li><strong>Incidentalomas.</strong> Imaging studies (especially CT and MRI) frequently find small abnormalities of unknown significance. Most are benign and would never have caused problems if undetected. But once found, they trigger follow-up imaging, biopsies, and anxiety.</li><li><strong>No actionable information.</strong> Many wellness tests report results without evidence-based interpretation. A "high" or "low" result doesn't mean you need to do anything specific, but anxious patients pursue treatment anyway.</li></ol><p>The medical maxim: "Only test if the result will change what you do." If you wouldn't do anything different with a positive result, the test is not worth doing.</p>`,
      },
      {
        heading: 'Full-body MRI screening',
        html: `<p>The poster child for the wellness testing trap. Companies like Prenuvo and Ezra market full-body MRI scans for $1,500-$2,500, claiming to "detect cancer early" and "give you peace of mind."</p><p>The evidence:</p><ul><li><strong>No mortality benefit demonstrated</strong> in any rigorous study</li><li><strong>40-50% false positive rate</strong>: roughly half of healthy adults will have at least one "abnormal" finding</li><li><strong>Most findings are benign</strong> incidentalomas: cysts, lipomas, hemangiomas, small nodules that would never have caused symptoms</li><li><strong>Cascade of follow-up</strong>: each abnormal finding triggers more imaging, possibly biopsies, possibly surgery</li><li><strong>Anxiety and overtreatment</strong> are real, measurable harms</li></ul><p>USPSTF and major radiology organizations (American College of Radiology, Royal College of Radiologists) actively recommend AGAINST whole-body MRI for asymptomatic adults. The American Cancer Society does not recommend it. Insurance does not cover it because it has no evidence base.</p><p>Marketing claims: "early detection saves lives." Reality: full-body MRI has not demonstrated mortality benefit in any controlled study. Targeted screening of specific organs in high-risk groups (lung CT for heavy smokers, mammography for women 40-74, etc.) has evidence; whole-body imaging does not.</p>`,
      },
      {
        heading: 'Direct-to-consumer genetic testing',
        html: `<p>Companies like 23andMe, AncestryDNA, and various clinical-grade DTC labs sell genetic testing for $99-$2,500. Tests range from ancestry analysis (relatively benign) to disease risk assessment (problematic) to "wellness panels" claiming to tell you about caffeine metabolism, athletic potential, and dietary needs.</p><p>What\'s legitimate:</p><ul><li><strong>BRCA1/BRCA2 testing</strong> for women with strong family history of breast or ovarian cancer (USPSTF Grade B for those with family history, Grade D for those without)</li><li><strong>Lynch syndrome testing</strong> for those with family history of colorectal or endometrial cancer</li><li><strong>Carrier testing</strong> for couples planning pregnancy with specific concerns</li><li><strong>Pharmacogenomic testing</strong> for specific medications where genotype affects dosing (warfarin, clopidogrel, some psychiatric medications)</li></ul><p>What\'s NOT evidence-based:</p><ul><li><strong>"Wellness" genetic panels</strong> claiming to predict caffeine metabolism, athletic ability, dietary needs — these have small effect sizes that don't translate to actionable advice</li><li><strong>Polygenic risk scores for common diseases</strong> (heart disease, type 2 diabetes) — not yet validated for individual decision-making</li><li><strong>Disease risk panels</strong> for cancer or Alzheimer's in adults without family history — high false alarm rate, low actionability</li></ul><p>Major problem: variants of unknown significance. Many genetic tests find variants that science can't yet interpret. You can't undo knowing about them, and they create anxiety without actionable information.</p>`,
      },
      {
        heading: 'Microbiome and food sensitivity testing',
        html: `<p>Microbiome testing (Viome, Thryve, BIOHM, others) and food sensitivity testing (LEAP, Cyrex, Everlywell, others) are heavily marketed and have no evidence base for diagnostic use.</p><p>Microbiome testing:</p><ul><li><strong>Marketing claim:</strong> analyze your gut bacteria, get personalized diet and supplement recommendations</li><li><strong>Reality:</strong> the gut microbiome is highly variable day-to-day, varies by sampling location, and has no validated reference ranges. Different labs give different results for the same person on the same day.</li><li><strong>Evidence:</strong> the field is too immature for clinical decision-making. Researchers themselves don't know how to interpret results for individual patients.</li><li><strong>USPSTF/AGA position:</strong> not recommended for any clinical purpose</li></ul><p>Food sensitivity testing (IgG-based):</p><ul><li><strong>Marketing claim:</strong> blood test identifies foods causing inflammation, fatigue, weight gain, and chronic symptoms</li><li><strong>Reality:</strong> IgG antibodies to foods reflect normal exposure, not pathologic response. Eliminating foods based on IgG results has no evidence of benefit and can lead to nutritional deficiency.</li><li><strong>Position of major medical organizations:</strong> AAAAI, EAACI, and others actively warn against IgG food sensitivity testing as having no validated diagnostic value.</li></ul><p>Both categories are marketed primarily through wellness clinics, naturopaths, and direct-to-consumer channels. Medical insurance does not cover them because they have no validated use.</p>`,
      },
      {
        heading: 'Other wellness tests with no evidence',
        html: `<ul><li><strong>Hair mineral analysis:</strong> claims to detect nutritional deficiencies and toxic exposures. No validated scientific basis. Different labs give different results for the same hair sample.</li><li><strong>Heavy metal testing in healthy adults:</strong> not recommended unless specific exposure suspected. False positives lead to unnecessary chelation therapy, which has its own risks.</li><li><strong>Comprehensive vitamin and mineral panels:</strong> most vitamin levels in healthy adults eating normal diets are within normal range. Testing rarely changes management. Vitamin D testing in particular has Grade I from USPSTF (insufficient evidence).</li><li><strong>"Adrenal fatigue" cortisol testing:</strong> "adrenal fatigue" is not a recognized medical diagnosis. Cortisol testing has specific clinical uses (diagnosing Cushing syndrome or Addison's disease) but does not validate a popular wellness diagnosis.</li><li><strong>"Biological age" calculators</strong> (epigenetic clocks, telomere length): research tools, not validated for clinical decision-making in individual patients.</li><li><strong>Heart rate variability (HRV) for general health monitoring:</strong> useful as a recovery indicator for athletes but not as a general health screen.</li></ul>`,
      },
      {
        heading: 'How to spot wellness testing red flags',
        html: `<p>Five marketing patterns that should make you skeptical:</p><ol><li><strong>"Personalized" or "comprehensive" without specifics about validation.</strong> Real personalized medicine is based on validated biomarkers with known clinical significance. "Personalized" wellness testing usually means "we run a panel and tell you about whatever shows up."</li><li><strong>Testimonials instead of clinical trials.</strong> If the marketing relies on customer success stories rather than peer-reviewed mortality or morbidity outcomes, it's not evidence-based.</li><li><strong>Bypassing doctors.</strong> Tests sold direct-to-consumer without physician interpretation often lack the clinical context to make sense of results.</li><li><strong>"Cutting-edge" or "ahead of mainstream medicine."</strong> Sometimes true; usually means "not validated yet" or "not validated at all."</li><li><strong>Combination upsells.</strong> Test → consultation → supplements → coaching. The test is the entry point to a recurring revenue stream, not the value being delivered.</li></ol><p>Legitimate uses of biomarker testing exist. Targeted USPSTF Grade A/B screenings, validated diagnostic tests for specific symptoms, FDA-approved companion diagnostics for medications — all have evidence and clinical value. The wellness industry's broad-spectrum testing approach generally does not.</p><p>If you're tempted by a wellness test, ask: "What peer-reviewed studies show this test improves health outcomes in healthy adults like me?" If the answer doesn't exist, the test isn't worth your money.</p>`,
      },
    ],
    faqs: [
      { question: 'Are full-body MRI scans worth getting?', answer: 'No. USPSTF and major radiology organizations actively recommend against whole-body MRI for asymptomatic adults. The 40-50% false positive rate triggers unnecessary follow-up, biopsies, and anxiety. No mortality benefit has been demonstrated. Companies like Prenuvo and Ezra market them aggressively despite the lack of evidence.' },
      { question: 'Does direct-to-consumer genetic testing actually work?', answer: 'Depends on the test. Ancestry tests are relatively benign. BRCA testing for those with family history is evidence-based. "Wellness" panels claiming to predict caffeine metabolism, athletic ability, or dietary needs are not validated. Disease risk panels in adults without family history have high false alarm rates and low actionability.' },
      { question: 'Is microbiome testing useful?', answer: 'Not yet. The gut microbiome is highly variable and has no validated reference ranges. Different labs give different results for the same person on the same day. Major gastroenterology organizations do not recommend microbiome testing for any clinical purpose. The science is too immature for clinical decision-making.' },
      { question: 'Are food sensitivity tests legitimate?', answer: 'No. IgG-based food sensitivity testing has been actively criticized by allergy organizations (AAAAI, EAACI) as having no validated diagnostic value. IgG antibodies to foods reflect normal exposure, not pathologic response. Eliminating foods based on IgG results can lead to nutritional deficiencies without benefit.' },
      { question: 'Should I get hair mineral analysis or heavy metal testing?', answer: 'Hair mineral analysis has no validated scientific basis. Heavy metal testing is recommended only when specific exposure is suspected (occupational, environmental, dietary). Routine testing in healthy adults generates false positives that lead to unnecessary chelation therapy, which has its own risks.' },
      { question: 'How do I know if a wellness test is legitimate?', answer: 'Ask: "What peer-reviewed studies show this test improves health outcomes in healthy adults like me?" Legitimate tests have validation studies in peer-reviewed journals. Marketing testimonials, "personalized" claims without specifics, and bypassing physicians are red flags. If USPSTF or major medical organizations don\'t recommend a test, you probably don\'t need it.' },
    ],
  },
];

export function getAllGuides(): Guide[] {
  return guides;
}

export function getGuideBySlug(slug: string): Guide | undefined {
  return guides.find((g) => g.slug === slug);
}
